### ISSUE TITLE
Repo broken

### ISSUE THREAD

**Issue by cdegroot** [bigtoast/sbt-thrift#2]
In your documentation, you refer to bigtoast.github.com/repo, but this repository does not exist. http://bigtoast.github.com/ shows what seems to be a merge conflict output :)

**Comment by bigtoast** [comment]
Thanks for the heads up. I am working on fixing it now.

-A

**Comment by bigtoast** [comment]
Fixed. I don't know how it got f'ed up but it did. I also added a html pages so the repo can be browsed.

http://bigtoast.github.com/repo
