### ISSUE TITLE
`thrift` invoked every build

### ISSUE THREAD

**Issue by jrray** [bigtoast/sbt-thrift#4]
The thrift files are compiled every time a build is performed, e.g., "compile." It would be great to avoid running `thift` if the thrift files haven't been changed.

**Comment by bigtoast** [comment]
Is this a problem? The thrift task executes for me in under a second
so I have never felt the penalty we pay by the unneeded code
regeneration.

-A

Andrew Headrick
916.476.8226
Friend us: http://www.facebook.com/ticketfly
Follow us: http://www.twitter.com/ticketfly
Check out what people are saying! http://www.ticketfly.com/category/news/

On Fri, Jun 8, 2012 at 2:33 PM, jrray
reply@reply.github.com
wrote:

**Comment by jrray** [comment]
It's good form for a build tool to not recompile things unless needed. It is possible there will be a project large enough with enough *.thrift sources that it becomes a nuisance.

sbt-protobuf does this, using FileFunction.cached.

**Comment by bigtoast** [comment]
Point taken. Ill look into FileFunction.cached

-A

Andrew Headrick
916.476.8226
Friend us: http://www.facebook.com/ticketfly
Follow us: http://www.twitter.com/ticketfly
Check out what people are saying! http://www.ticketfly.com/category/news/

On Sun, Jun 10, 2012 at 12:08 AM, jrray
reply@reply.github.com
wrote:

**Comment by bigtoast** [comment]
fixed. finally had some time.
