### ISSUE TITLE
"~ compile" does not detect changes to thrift files

### ISSUE THREAD

**Issue by jrray** [bigtoast/sbt-thrift#5]
When I'm using "~ compile" to repeatedly build my project on file changes, sbt is not noticing when I change the thrift files.

I have to break out of "~ compile" and start it again for the thrift files to be compiled.

**Comment by bigtoast** [comment]
Hmm. I have never tried it with auto compile before. Good find. I will
try to get that in there and make it work.

How is the plugin working for you outside this problem? If you have
any other requests or suggestions please let me know and Ill try to
get them in.

All the best,
Andy

Andrew Headrick
916.476.8226
Backend Architect
Ticketfly
Friend us: http://www.facebook.com/ticketfly
Follow us: http://www.twitter.com/ticketfly
Check out what people are saying! http://www.ticketfly.com/category/news/

On Fri, Jun 8, 2012 at 2:35 PM, jrray
reply@reply.github.com
wrote:

**Comment by jrray** [comment]
Thanks, I just started using this today as I'm am evaluating Thrift for my project.

It is working fine for me otherwise.

**Comment by jrray** [comment]
I found this example of how it is done:

https://github.com/indrajitr/sbt-yui-compressor/blob/master/src/main/scala/Plugin.scala#L75

Edit: I think coffeescripted-sbt is a better example: https://github.com/softprops/coffeescripted-sbt/blob/master/src/main/scala/coffeescript.scala

I have my own plugin that is based on sbt-protobuf and I found the coffeescript plugin to be closer in design to my plugin. I added the 'filter' and 'excludeFilter' SettingKeys, a *SourcesTask method, and added the 'watchedSources' bits.

**Comment by bigtoast** [comment]
Thanks for the link. I should have some time later in the week to attack it.

All the best,
Andy

Andrew Headrick
916.476.8226
Friend us: http://www.facebook.com/ticketfly
Follow us: http://www.twitter.com/ticketfly
Check out what people are saying! http://www.ticketfly.com/category/news/

On Sun, Jun 10, 2012 at 12:08 AM, jrray
reply@reply.github.com
wrote:

**Comment by bigtoast** [comment]
Finally had some time. Fixed.
