### ISSUE TITLE
-out vs -o

### ISSUE THREAD

**Issue by MasseGuillaume** [bigtoast/sbt-thrift#7]
I think you should replace -o with -out.

In intellij idea I have project Server that depends on project Api. Since the output is on Api/target/src_managed/gen-java and not directly in Api/target/src_managed idea give me import errors.

For backward compatibility you could have the key setting thriftOutputDir to gen-java

**Comment by janstenpickle** [comment]
@MasseGuillaume I've had the same issue, as this repo hasn't been touched in 2 years I've created a new version here: https://github.com/intenthq/sbt-thrift-plugin
